{% set name = "pbls" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://git.sr.ht/~rrc/pbls/archive/{{ version }}.tar.gz
  sha256: 77f2a8fd3c19a5e38a5b090b92ee1f2e7daf4d5f145e51fbf6c92c35661a6e10

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - pbls &  # [not win]
    - exe_pid=$!  # [not win]
    - trap "kill -SIGTERM ${exe_pid}" SIGTERM  # [not win]
    - start /b pbls   # [win]
    - if %errorlevel% neq 0 exit %errorlevel%  # [win]
    - taskkill /F /im pbls.exe  # [win]
    - if %errorlevel% neq 0 exit %errorlevel%  # [win]

about:
  home: https://git.sr.ht/~rrc/pbls
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: pbls is a Language Server for protobuf.
  dev_url: https://git.sr.ht/~rrc/pbls

extra:
  recipe-maintainers:
    - danielnachun
